import "./globals.css";
// @ts-ignore
import type { Metadata } from "next";
// @ts-ignore

import { Inter } from "next/font/google";
import HeaderComponent from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("children :>> ", children);
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderComponent></HeaderComponent>

        <div>{children}</div>
        <HeaderComponent></HeaderComponent>
        <footer>Burası footer</footer>
      </body>
    </html>
  );
}
